language: java

jdk:
  - openjdk8
  - openjdk10

cache:
  directories:
    - $HOME/.m2

script:
  - mvn clean verify

git:
  depth: 3

matrix:
  include:
  - jdk: openjdk10
    before_install:
    - rm "${JAVA_HOME}/lib/security/cacerts"
    - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
